name: Executar script AutoIt3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Executar script AutoIt3
        uses: crazy-max/ghaction-autoit@v1
        with:
          script: ./Cadastro\ de\ Entregas\ por\ Grupo/cadastroDeEntregasPorGrupo.au3