name: Testes com AutoIt

on: [push, pull_request]

jobs:
  executar_testes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código-fonte
      uses: actions/checkout@v4
      
    - name: Configurar AutoIt
      run: |
        wget "https://www.autoitscript.com/site/autoit/downloads/"
        chmod +x AutoIt_installer.exe
        ./AutoIt_installer.exe /SILENT /VERYSILENT
        
    - name: Executar testes AutoIt
      run: |
        Get-ChildItem -Recurse -Filter *.au3 | ForEach-Object { Start-Process AutoIt3.exe -ArgumentList $_.FullName -Wait }
